/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface AddArticle {}
  interface AddArticleAttributes extends StencilHTMLAttributes {}

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface ArticleDetails {}
  interface ArticleDetailsAttributes extends StencilHTMLAttributes {}

  interface EditArticle {}
  interface EditArticleAttributes extends StencilHTMLAttributes {}

  interface PageAllArticles {}
  interface PageAllArticlesAttributes extends StencilHTMLAttributes {}

  interface ViewDetails {
    'arts': any;
    'match': MatchResults;
  }
  interface ViewDetailsAttributes extends StencilHTMLAttributes {
    'arts'?: any;
    'match'?: MatchResults;
  }

  interface ViewAll {}
  interface ViewAllAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AddArticle': Components.AddArticle;
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'ArticleDetails': Components.ArticleDetails;
    'EditArticle': Components.EditArticle;
    'PageAllArticles': Components.PageAllArticles;
    'ViewDetails': Components.ViewDetails;
    'ViewAll': Components.ViewAll;
  }

  interface StencilIntrinsicElements {
    'add-article': Components.AddArticleAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'article-details': Components.ArticleDetailsAttributes;
    'edit-article': Components.EditArticleAttributes;
    'page-all-articles': Components.PageAllArticlesAttributes;
    'view-details': Components.ViewDetailsAttributes;
    'view-all': Components.ViewAllAttributes;
  }


  interface HTMLAddArticleElement extends Components.AddArticle, HTMLStencilElement {}
  var HTMLAddArticleElement: {
    prototype: HTMLAddArticleElement;
    new (): HTMLAddArticleElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLArticleDetailsElement extends Components.ArticleDetails, HTMLStencilElement {}
  var HTMLArticleDetailsElement: {
    prototype: HTMLArticleDetailsElement;
    new (): HTMLArticleDetailsElement;
  };

  interface HTMLEditArticleElement extends Components.EditArticle, HTMLStencilElement {}
  var HTMLEditArticleElement: {
    prototype: HTMLEditArticleElement;
    new (): HTMLEditArticleElement;
  };

  interface HTMLPageAllArticlesElement extends Components.PageAllArticles, HTMLStencilElement {}
  var HTMLPageAllArticlesElement: {
    prototype: HTMLPageAllArticlesElement;
    new (): HTMLPageAllArticlesElement;
  };

  interface HTMLViewDetailsElement extends Components.ViewDetails, HTMLStencilElement {}
  var HTMLViewDetailsElement: {
    prototype: HTMLViewDetailsElement;
    new (): HTMLViewDetailsElement;
  };

  interface HTMLViewAllElement extends Components.ViewAll, HTMLStencilElement {}
  var HTMLViewAllElement: {
    prototype: HTMLViewAllElement;
    new (): HTMLViewAllElement;
  };

  interface HTMLElementTagNameMap {
    'add-article': HTMLAddArticleElement
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'article-details': HTMLArticleDetailsElement
    'edit-article': HTMLEditArticleElement
    'page-all-articles': HTMLPageAllArticlesElement
    'view-details': HTMLViewDetailsElement
    'view-all': HTMLViewAllElement
  }

  interface ElementTagNameMap {
    'add-article': HTMLAddArticleElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'article-details': HTMLArticleDetailsElement;
    'edit-article': HTMLEditArticleElement;
    'page-all-articles': HTMLPageAllArticlesElement;
    'view-details': HTMLViewDetailsElement;
    'view-all': HTMLViewAllElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
